### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Ensnare2** [radxa-pkg/aic8800#23]
So I have a mini pc with this exact dongle. I want to install debian but when trying to get the wifi to work I try using your packages and it just says it needs other packages, dkms, etc.

Is there a simple way to do this that im just missing? or do i need wifi to get the wifi dongle for this to work?

**Comment by RadxaYuntian** [comment]
You should contact your dongle seller for matching driver and installation guide. We are only supporting this repository for our own products.

If you want to use our packages on other systems then yes you will need to install `dkms` and matching kernel headers. That's same for other dkms packages provided by Debian, so yes you will need network working first to use the package, since it has to download those resources to be able to build the driver. It is not a binary package.
